#!/bin/sh

if [ $# -ne 1 ]; then
    exit
fi


cmd="export CGO_ENABLED=0 && export GOOS=linux && export GOARCH=$1 && go build  -v -ldflags=\"-s -w\" ."
path="$(PWD/#$HOME/"/root")"
sudo docker exec -w $path -it golang bash -c $cmd

